Traceback (most recent call last):
  File "/eos/user/z/zhenxuan/hhwwgg/DiPhotonJetsBox_MGG_2017/job_82/DiPhotonJetsBox_MGG_2017_executable_job82.py", line 13, in <module>
    run_analysis(config)
  File "/afs/cern.ch/user/z/zhenxuan/HiggsDNA/higgs_dna/analysis.py", line 52, in run_analysis
    events, sum_weights = AnalysisManager.load_events(config["files"], config["branches"])
  File "/afs/cern.ch/user/z/zhenxuan/HiggsDNA/higgs_dna/analysis.py", line 465, in load_events
    with uproot.open(file, timeout = 500) as f:
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/reading.py", line 141, in open
    file = ReadOnlyFile(
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/reading.py", line 580, in __init__
    self._source = Source(
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/source/xrootd.py", line 272, in __init__
    self._open()
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/source/xrootd.py", line 275, in _open
    self._resource = XRootDResource(self._file_path, self._timeout)
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/source/xrootd.py", line 83, in __init__
    self._open()
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/source/xrootd.py", line 92, in _open
    self._xrd_error(status)
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/source/xrootd.py", line 118, in _xrd_error
    raise OSError(
OSError: XRootD error: [ERROR] Operation expired
in file root://cms-xrd-global.cern.ch//store/mc/RunIIFall17NanoAODv7/DiPhotonJetsBox_MGG-80toInf_13TeV-Sherpa/NANOAODSIM/PU2017_12Apr2018_Nano02Apr2020_102X_mc2017_realistic_v8-v1/70000/AAEAD36A-6F85-7E41-A888-F4A0BAA4A22B.root
