Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site
Traceback (most recent call last):
  File "/eos/user/z/zhenxuan/hhwwgg/QCD_HT50to100_2017/job_3/QCD_HT50to100_2017_executable_job3.py", line 4, in <module>
    from higgs_dna.analysis import run_analysis
  File "/afs/cern.ch/user/z/zhenxuan/HiggsDNA/higgs_dna/analysis.py", line 18, in <module>
    from higgs_dna.job_management.managers import LocalManager, CondorManager
  File "/afs/cern.ch/user/z/zhenxuan/HiggsDNA/higgs_dna/job_management/managers.py", line 22, in <module>
    import enlighten
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/enlighten/__init__.py", line 14, in <module>
    from enlighten.counter import Counter, StatusBar, SubCounter
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/enlighten/counter.py", line 19, in <module>
    from enlighten.manager import get_manager
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/enlighten/manager.py", line 21, in <module>
    from IPython import get_ipython
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/IPython/__init__.py", line 52, in <module>
    from .terminal.embed import embed
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/IPython/terminal/embed.py", line 17, in <module>
    from IPython.terminal.ipapp import load_default_config
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/IPython/terminal/ipapp.py", line 29, in <module>
    from IPython.core.magics import (
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/IPython/core/magics/__init__.py", line 18, in <module>
    from .code import CodeMagics, MacroToEdit
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/IPython/core/magics/code.py", line 23, in <module>
    from urllib.request import Request, urlopen
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/urllib/request.py", line 102, in <module>
    from urllib.error import URLError, HTTPError, ContentTooShortError
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1074, in get_data
OSError: [Errno 5] Input/output error
