Traceback (most recent call last):
  File "/eos/user/z/zhenxuan/hhwwgg/TTGJets_2017/job_15/TTGJets_2017_executable_job15.py", line 4, in <module>
    from higgs_dna.analysis import run_analysis
  File "/afs/cern.ch/user/z/zhenxuan/HiggsDNA/higgs_dna/analysis.py", line 10, in <module>
    import uproot
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/__init__.py", line 78, in <module>
    import uproot.extras
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/extras.py", line 17, in <module>
    from uproot._util import parse_version
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/_util.py", line 19, in <module>
    import setuptools
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/setuptools/__init__.py", line 18, in <module>
    from setuptools.dist import Distribution
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/setuptools/dist.py", line 33, in <module>
    from setuptools.extern import nspektr
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/setuptools/extern/__init__.py", line 52, in create_module
    return self.load_module(spec.name)
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/setuptools/extern/__init__.py", line 37, in load_module
    __import__(extant)
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/setuptools/_vendor/nspektr/__init__.py", line 11, in <module>
    from ._compat import metadata, repair_extras
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/setuptools/_vendor/nspektr/_compat.py", line 6, in <module>
    import importlib.metadata as metadata
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1074, in get_data
OSError: [Errno 5] Input/output error
