Traceback (most recent call last):
  File "/eos/user/z/zhenxuan/hhwwgg/GluGluToRadionToHHTo2B2G_M-550_2017/job_3/GluGluToRadionToHHTo2B2G_M-550_2017_executable_job3.py", line 13, in <module>
    run_analysis(config)
  File "/afs/cern.ch/user/z/zhenxuan/HiggsDNA/higgs_dna/analysis.py", line 77, in run_analysis
    tag_sequence = TagSequence(
  File "/afs/cern.ch/user/z/zhenxuan/HiggsDNA/higgs_dna/taggers/tag_sequence.py", line 50, in __init__
    m_tagger = self.create_tagger(tagger)
  File "/afs/cern.ch/user/z/zhenxuan/HiggsDNA/higgs_dna/taggers/tag_sequence.py", line 63, in create_tagger
    module = importlib.import_module(config["module_name"])
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/afs/cern.ch/user/z/zhenxuan/HiggsDNA/higgs_dna/taggers/diphoton_tagger.py", line 4, in <module>
    import numba
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/numba/__init__.py", line 19, in <module>
    from numba.core import config
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/numba/core/config.py", line 9, in <module>
    import yaml
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/yaml/__init__.py", line 8, in <module>
    from .loader import *
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/yaml/loader.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1074, in get_data
OSError: [Errno 5] Input/output error
